var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

var DISNEY_GAMES_VERSION="1.7.21";var disneyGamesUtils=function(){function h(){if(x.length>0){var o=x.shift();p(o.url,o.type,o.callback!=null?function(){o.callback();h()}:function(){h()})}else r=false}function p(o,y,C,w){var t;if(y==B){t=document.createElement("script");t.setAttribute("type","text/javascript");t.setAttribute("src",o);w&&t.setAttribute("id",w);if(C!=null)if(t.readyState)t.onreadystatechange=function(){if(t.readyState=="loaded"||t.readyState=="complete"){t.onreadstatechange=null;C()}};else t.onload=function(){C()}}else if(y==
D){t=document.createElement("link");t.setAttribute("rel","stylesheet");t.setAttribute("type","text/css");t.setAttribute("href",o);C!=null&&C()}document.getElementsByTagName("head")[0].appendChild(t)}var x=[],r=false,B="script",D="css";return{embedSupportItem:p,embedMultipleSupportItems:function(o,y){var C=o.length;if(C==0)y();else{o[C-1].callback=y;for(var w=0;w<C;w++)x.push(o[w]);if(!r){r=true;h()}}},removeSupportItem:function(o){(o=document.getElementById(o))&&o.parentNode.removeChild(o)},querySt:function(o){hu=
window.location.search.substring(1);gy=hu.split("&");for(i=0;i<gy.length;i++){ft=gy[i].split("=");if(ft[0]==o)return ft[1]}return""},addLoadEvent:function(o){if(typeof window.addEventListener!="undefined")window.addEventListener("load",o,false);else if(typeof document.addEventListener!="undefined")document.addEventListener("load",o,false);else if(typeof window.attachEvent!="undefined")window.attachEvent("onload",o);else if(typeof window.onload=="function"){var y=window.onload;window.onload=function(){y();
o()}}else window.onload=o}}}();var disneyGames=function(){function h(a,c){var e=null,q=u[c.provider||"default"];if(q)if(typeof c.elementId==A)e="Missing elementId.";else q.isConfigValid(c)||(e="Config is invalid.");else e="Provider was not found";if(e!=null)alert("Game Container Error: "+e);else{var G;switch(a){case W:G=function(){var z={};z.config=c;z.id=z.config.contentId;z.provider=q;z.wrapper=document.getElementById(z.config.elementId);z.paused=false;j[z.id]=z;z.provider.isCompleteConfig()?p(z):z.provider.fetchConfig(z)};break;
case k:G=function(){disneyGamesSwfObject.embedSWF(X,c.elementId,aa,N,ba,U,{cmsId:c.contentId},{scale:"exactfit",allowScriptAccess:"always",wmode:"opaque",base:l},{id:c.elementId,name:c.elementId,"class":"testbar"})}}d?G():f.push(G)}}function p(a){g&&g.config.elementId==a.config.elementId&&B();if(y())a.config.showPlayBtnOverlay=true;a.wrapper.style.width=w(a)+"px";a.wrapper.style.height=t(a)+"px";a.wrapper.style.backgroundColor=a.config.color||Q;a.wrapper.style.backgroundImage="";a.wrapper.style.margin=
"0px";a.wrapper.style.position="relative";a.wrapper.innerHTML="";x(a);var c;a:{for(c=0;c<v.length;c++)if(v[c].test(b)){c=true;break a}c=false}if(c)if(g&&g.iframe&&g.iframe.parentNode!=null||a.config.showPlayBtnOverlay)D(a);else{o(a);r(a)}else{c="You are not authorized to host this game on "+window.location.href+". Please contact your Disney producer for more details.";document.getElementById(a.config.elementId).innerHTML=c}}function x(a){var c=a.config.img750x500!==""?a.config.img750x500:O,e=w(a),
q=t(a);a.overlayImg=document.createElement("img");a.overlayImg.className=V;a.overlayImg.setAttribute("src",c);a.overlayImg.style.width=e+"px";a.overlayImg.style.height=q+"px";a.overlay=document.createElement("img");a.overlay.className=J;a.overlay.setAttribute("src",R);a.overlay.style.width=e+"px";a.overlay.style.height=q+"px";a.overlay.onclick=function(){if(g){if(g!=a){B(true);r(a)}}else r(a)};a.wrapper.appendChild(a.overlayImg);a.wrapper.appendChild(a.overlay)}function r(a){if(y()&&a.config.html5URL)if(document.createElement("canvas").getContext)window.location=
a.config.html5URL;else{o(a);a.wrapper.style.backgroundImage="url("+P+")"}else{o(a);g=a;window.location.href.lastIndexOf("/cds/")==-1?H(a):C(a)}}function B(a){K(true);var c=g;if(c.iframe){disneyGamesCommunication.unregisterChild();c.iframe.parentNode&&c.iframe.parentNode.removeChild(c.iframe);c.iframe=null}a==true&&D(g);g=null}function D(a){a.overlayImg.style.display="block";a.overlay.style.display="block"}function o(a){a.overlayImg.style.display="none";a.overlay.style.display="none"}function y(){return navigator.userAgent.match(/(ipod|iphone|ipad|android|silk|iemobile)/i)}
function C(a){var c=a.provider.getIframeURL(a);if(c===P){a.wrapper.style.backgroundImage="url("+c+")";a.iframe=null}else{var e=document.createElement("iframe");e.setAttribute("id",s);e.setAttribute("src",c);e.setAttribute("width",w(a));e.setAttribute("height",t(a));e.setAttribute("frameborder",0);e.setAttribute("scrolling","no");e.setAttribute("allowTransparency","true");e.setAttribute("style","background-color: transparent");a.iframe=e;a.wrapper.appendChild(a.iframe);c.indexOf(window.location.hostname)!==
-1&&disneyGamesCommunication.registerChild(a.iframe.contentWindow)}}function w(a){var c=L;if(a.config.shrinkToFit!==true&&a.config.shrinkToFit!=="true")if(a.config.width)c=Math.max(a.config.width,L);return c}function t(a){var c=Y;if(a.config.shrinkToFit!==true&&a.config.shrinkToFit!=="true")if(a.config.height)c=Math.max(a.config.height,Y);return c}function K(a){m&&clearTimeout(m);m=null;var c=document.getElementById(E);c&&c.parentNode.removeChild(c);if(!a&&g&&(!g.iframe||!g.iframe.parentNode))C(g)}
function H(a){window.googletag=window.googletag||{};googletag.cmd=googletag.cmd||[];m&&K(true);var c=document.getElementById(E),e=Z,q=a.config.adSlot;if(q){googletag.cmd.push(function(){q.setTargeting("assetId",a.config.assetId);q.setTargeting("assetName",a.config.assetName);q.setTargeting("assetType",a.config.assetType);q.setTargeting("bu",a.config.bu);q.setTargeting("gameName",a.config.gameName);q.setTargeting("gameType",a.config.gameType);q.setTargeting("genre",a.config.genre);q.setTargeting("owner",
a.config.owner);q.setTargeting("property",a.config.property)});c&&c.parentNode.removeChild(c);c=document.createElement("div");c.setAttribute("id",E);a.wrapper.appendChild(c);googletag.cmd.push(function(){googletag.display(E);n||googletag.pubads().refresh([q]);n=false})}else c&&googletag.display(E);c||(e=0);m=setTimeout(function(){K()},e)}function ca(){d=true;for(var a=0;a<f.length;a++)f[a]();f=[]}var A="undefined",S="";(function(){var a=document.getElementsByTagName("script"),c="";a=a[a.length-1].src.split("/");
if(a.length>0)c=a[a.length-1];a=c.lastIndexOf("-");if(a!=-1){c=c.substring(a+1,c.length-3);isNaN(parseInt(c))||(S=c)}if(typeof DISNEY_GAMES_VERSION==A)window.DISNEY_GAMES_VERSION=S})();var L=750,Y=500,s="DisneyGamesIFrame",J="disneyGamesPlayBtnOverlay",V="disneyGamesPlayBtnImg",ba="9.0.0",F="//"+(window.location.protocol==="https:"?"s.dolimg.com":"a.dolimg.com")+"/media/en-US/games/syndication/",l=F+"swf/",I=F+"img/",$=F+"css/disneygames"+(S!=""?"-"+S:"")+".css",T=window.location.protocol+"//"+window.location.host+
"/games/syndication/iframeGame",M=window.location.protocol+"//web.archive.org/web/20121130011817/http://tv.disney.go.com/disneychannel/global/game/iframeChild.html",U=l+"expressInstall.swf",O=I+"teaserBackground.jpg",R=I+"playButton.png",P=I+"unsupportedBrowser.jpg",X=l+"testBar_1_2_0.swf",aa=750,N=110,Q="000000",E="div-gpt-ad-gamesloader",Z=1E4,W="game",k="testbar",b=window.location.hostname,d=false,f=[],g=null,j={},m=null,n=true,v=[/\.go\.com/,/diznee\.net/,/\.digisynd\.com/,/\.disneychannel\.com/,/\.disney\.com/,/a\.dolimg\.com/],u={};
u["default"]=function(){return{isConfigValid:function(a){return!(typeof a.contentId==A||a.contentId==""||parseInt(a.contentId)==NaN)},isCompleteConfig:function(){return false},fetchConfig:function(a){var c="//web.archive.org/web/20121130011817/http://home.disney.go.com/dxd/dynamic/getGameInfo";if(a.config.internal)c="//web.archive.org/web/20121130011817/http://home.disney.go.com/dxd/dynamic/getGameInfoInternal";c+="?gameId="+a.id;c+="&jsonp=disneyGames.processConfigAddGame";disneyGamesUtils.embedSupportItem(c,"script",null,"DisneyGameConfigInfo"+a.id)},getIframeURL:function(a){var c=
"",e=a.config.html5URL!=="",q=a.config.fileURL!=="",G=false;if(e&&q)if(a.config.preferHTML5&&disneyGamesHTML5.isBrowserSupported())a.config.iframePath=a.config.html5URL;else G=true;else if(e)a.config.iframePath=disneyGamesHTML5.isBrowserSupported()?a.config.html5URL:P;else G=true;if(G){c=T;if(String(window.location.hostname).indexOf("tv.disney.go.com")!=-1)c=M;a.config.iframePath=a.config.iframePath||c;c=a.config;e="?";e+="techType="+c.techType;e+="&apiVersion="+c.apiVersion;e+="&fileURL="+encodeURIComponent(c.fileURL);
e+="&width="+c.width;e+="&height="+c.height;e+="&title="+c.title;e+="&minimumFlashPlayerVersion="+c.minimumFlashPlayerVersion;e+="&color="+(typeof c.color!=A?c.color:Q);e+="&wmode="+(typeof c.wmode!=A?c.wmode:"window");e+="&shrinkToFit="+(typeof c.shrinkToFit!=A?c.shrinkToFit:false);e+="&assetId="+c.assetId;e+="&assetName="+encodeURIComponent(c.assetName);e+="&assetType="+c.assetType;e+="&bu="+c.bu;e+="&gameName="+c.gameName;e+="&gameType="+c.gameType;e+="&genre="+c.genre;e+="&owner="+c.owner;e+=
"&property="+c.property;c=e}a=a.config.iframePath;a+=c;return a}}}();u.create=function(){return{isConfigValid:function(a){if(!a.contentId)return false;var c=a.contentId.split("-");if(c.length<3)return false;a.client=c[0];a.activityName=c[1];a.instanceName=c.slice(2).join("-");if(!a.client||!a.activityName||!a.instanceName)return false;return true},isCompleteConfig:function(){return false},fetchConfig:function(a){var c="";c+="?omnitureSite="+(typeof cto!=A&&typeof cto.site!=A?cto.site:"defaultSite");
c+="&omnitureSiteSection="+(typeof cto!=A&&typeof cto.siteSection!=A?cto.siteSection:"siteSection");var e;e=a.config.infoUrl?a.config.infoUrl:String(window.location.hostname).indexOf("tv.disney.go.com")!=-1?"https://web.archive.org/web/20121130011817/http://tv.disney.go.com/create/syndication":"https://web.archive.org/web/20121130011817/http://disney.go.com/create/syndication";e+="/"+a.config.client+"/apps/"+a.config.activityName+"/"+a.config.instanceName+".json";e+=c;e+="&_ROOT_callback=disneyGames.processConfigAddGame";disneyGamesUtils.embedSupportItem(e,"script",null,"DisneyGameConfigInfo"+
a.id)},getIframeURL:function(a){a.config.iframeURL=a.config.iframeURL||T;return a.config.iframeURL}}}();(function(){var a=[],c;a:{c=document.getElementsByTagName("link");for(var e=0;e<c.length;e++)if(c[e].href.indexOf($)!=-1){c=true;break a}c=false}if(!c){c={url:$,type:"css"};a.push(c)}a.length>0?disneyGamesUtils.embedMultipleSupportItems(a,ca):ca()})();return{addGame:function(a){h(W,a)},addTestBar:function(a){h(k,a)},hideGame:function(){if(g&&g.iframe){if(!g.paused){disneyGamesCommunication.sendMessage("setVolume",
0);disneyGamesCommunication.sendMessage("setPause",true);g.paused=true}g.iframe.style.visibility="hidden";g.iframe.style.width="1px";g.iframe.style.height="1px"}},showGame:function(){if(g&&g.iframe){if(g.paused){disneyGamesCommunication.sendMessage("setVolume",1);disneyGamesCommunication.sendMessage("setPause",false);g.paused=false}g.iframe.style.visibility="visible";g.iframe.style.width=w(g)+"px";g.iframe.style.height=t(g)+"px"}},resize:function(a,c){var e=document.getElementById(s);e.style.width=
a+"px";e.style.height=c+"px"},removeGame:B,processConfigAddGame:function(a){var c;if(a.assetId)c=a;else{var e=c={};e.height=a.height;e.width=a.width;e.techType=a.type;e.fileURL=a.fileUrl;e.html5URL=a.html5Url;e.title=a.title;e.img750x500=a.images.img750x500;e.minimumFlashPlayerVersion=a.minimumFlashPlayerVersion;if(!e.minimumFlashPlayerVersion)e.minimumFlashPlayerVersion="10";e.apiVersion=typeof a.apiUrl!=A?"2.5":typeof a.shellUrl!=A?"1.0":"";e.assetId=a.id;e.assetName=a.reportingAssetName;e.assetType=
"gam";a=a.reportingAssetName.split("|");e.bu=a[1];e.property=a[2];e.owner=a[3];e.gameType=a[4];e.genre=a[5];e.gameName=a[7]}if(window.location.protocol==="https:"){c.fileURL=c.fileURL.replace("https://web.archive.org/web/20121130011817/http://a.dolimg.com","https://web.archive.org/web/20121130011817/https://s.dolimg.com");c.img750x500=c.img750x500.replace("https://web.archive.org/web/20121130011817/http://a.dolimg.com","https://web.archive.org/web/20121130011817/https://s.dolimg.com")}if(c.minimumFlashPlayerVersion=="11")c.wmode="direct";e=j[String(c.assetId)];var q;if(e){for(q in c)e.config[q]=c[q];p(e)}},removeAd:K,disableAutoUnload:function(){if(m){clearTimeout(m);
m=null}}}}();function disneyGamesHideGame(){disneyGames.hideGame()}function disneyGamesShowGame(){disneyGames.showGame()}function disneyGamesResize(h,p){disneyGames.resize(h,p)}function removeAd(){disneyGames.removeAd()}function disableAutoUnload(){disneyGames.disableAutoUnload()};var disneyGamesCommunication=function(){var h=[],p=null,x=parent!=this&&parent.window!=window?parent.window:null;return{sendMessage:function(r,B,D){var o=false;if(!D)if(p)try{var y=p.disneyGamesSendMessage(r,B,true);o=y?y:o}catch(C){}else if(x)if(x)try{var w=x.disneyGamesSendMessage(r,B,true);o=w?w:o}catch(t){}D=h.length;if(D==0)r=false;else{y=false;for(w=0;w<D;w++)try{var K=h[w](r,B);if(typeof K!="undefined"&&K)y=K}catch(H){}r=y}return r?r:o},addMessageListener:function(r){if(typeof r!="function")return null;
h.push(r);return r},addFlashMessageListener:function(r,B){typeof document[r]!="undefined"&&h.push(function(D,o){return typeof document[r]!="undefined"&&typeof document[r][B]!="undefined"?document[r][B](D,o):false})},clearMessageListeners:function(){h=[]},registerChild:function(r){p=r},unregisterChild:function(){p=null}}}();function disneyGamesSendMessage(h,p,x){disneyGamesCommunication.sendMessage(h,p,x)}function disneyGamesAddMessageListener(h){disneyGamesCommunication.addMessageListener(h)}
function disneyGamesAddFlashMessageListener(h,p){disneyGamesCommunication.addFlashMessageListener(h,p)}function disneyGamesClearMessageListeners(){disneyGamesCommunication.clearMessageListeners()};function DisneyGamesHTML5(){this.info={};this.minBrowser=[{browserType:"MSIE",platformType:"Win",minVersion:9},{browserType:"Chrome",platformType:"",minVersion:5},{browserType:"Firefox",platformType:"",minVersion:3.5},{browserType:"Safari",platformType:"Win",minVersion:4},{browserType:"Safari",platformType:"Mac",minVersion:4},{browserType:"Safari",platformType:"iPhone",minVersion:4},{browserType:"Safari",platformType:"iPad",minVersion:4},{browserType:"Safari",platformType:"iPod",minVersion:4}]}
DisneyGamesHTML5.prototype.detectBrowser=function(h){this.info.platformType=h.platform;this.info.browserName=h.appName;this.info.browserVersion=parseFloat(h.appVersion);this.info.iDevice=false;this.info.touchDevice=false;if(h.platform.indexOf("iPhone")!=-1){this.info.iDevice=true;this.info.touchDevice=true;this.info.platformType="iPhone";if(/OS (\d+\_\d+)/.test(h.userAgent)){var p=RegExp.$1;p=p.replace("_",".");this.info.platformVersion=parseFloat(p)}}else if(h.platform.indexOf("iPod")!=-1){this.info.iDevice=
true;this.info.touchDevice=true;this.info.platformType="iPod";if(/OS (\d+\_\d+)/.test(h.userAgent)){p=RegExp.$1;p=p.replace("_",".");this.info.platformVersion=parseFloat(p)}}else if(h.platform.indexOf("iPad")!=-1){this.info.iDevice=true;this.info.touchDevice=true;this.info.platformType="iPad";if(/OS (\d+\_\d+)/.test(h.userAgent)){p=RegExp.$1;p=p.replace("_",".");this.info.platformVersion=parseFloat(p)}}else if(h.userAgent.indexOf("Android")!=-1){this.info.touchDevice=true;this.info.platformType="Android";
if(/Android (\d+\.\d+)/.test(h.userAgent))this.info.platformVersion=new Number(RegExp.$1)}else if(h.userAgent.indexOf("Silk")!=-1||h.userAgent.indexOf("Kindle")!=-1){this.info.touchDevice=true;this.info.platformType="Android";this.info.platformVersion="2.3.4"}else if(h.userAgent.indexOf("IEMobile")!=-1){this.info.touchDevice=true;this.info.platformType="IEMobile";if(/IEMobile\/(\d+\.\d+)/.test(h.userAgent))this.info.platformVersion=new Number(RegExp.$1)}else if(h.platform.indexOf("Win")!=-1){this.info.platformType=
"Win";this.info.platformVersion=0}else if(h.platform.indexOf("Mac")!=-1){this.info.platformType="Mac";if(/OS X (\d+\_\d+)/.test(h.userAgent)){p=RegExp.$1;p=p.replace("_",".");this.info.platformVersion=parseFloat(p)}}else if(h.platform.indexOf("Linux")!=-1){this.info.platformType="Linux";this.info.platformVersion=0}if(h.userAgent.indexOf("Firefox")!=-1){this.info.browserName="Firefox";if(/Firefox[\/\s](\d+\.\d+)/.test(h.userAgent))this.info.browserVersion=new Number(RegExp.$1)}else if(h.userAgent.indexOf("MSIE")!=
-1){this.info.browserName="MSIE";if(/MSIE (\d+\.\d+);/.test(h.userAgent))this.info.browserVersion=new Number(RegExp.$1)}else if(h.userAgent.indexOf("Opera")!=-1){this.info.browserName="Opera";if(/Opera[\/\s](\d+\.\d+)/.test(h.userAgent))this.info.browserVersion=new Number(RegExp.$1)}else if(h.userAgent.indexOf("Chrome")!=-1){this.info.browserName="Chrome";if(/Chrome[\/\s](\d+\.\d+)/.test(h.userAgent))this.info.browserVersion=new Number(RegExp.$1)}else if(h.userAgent.indexOf("Safari")!=-1){this.info.browserName=
"Safari";if(/Version[\/\s](\d+\.\d+)/.test(h.userAgent))this.info.browserVersion=new Number(RegExp.$1)}else if(h.userAgent.indexOf("Netscape")!=-1){this.info.browserName="Netscape";if(/Netscape[\/\s](\d+\.\d+)/.test(h.userAgent))this.info.browserVersion=new Number(RegExp.$1)}else if(h.userAgent.indexOf("Konqueror")!=-1){this.info.browserName="Konqueror";if(/KHTML[\/\s](\d+\.\d+)/.test(h.userAgent))this.info.browserVersion=new Number(RegExp.$1)}else if(this.info.iDevice)this.info.browserName="Safari";
this.info.browserType=h.userAgent.indexOf("WebKit")!=-1?"WebKit":this.info.browserName;this.info.legacyIEFilterDOMPipe=this.info.browserName=="MSIE"&&this.info.browserVersion<9?true:false;h=window.WebKitCSSMatrix||window.MSCSSMatrix||window.MozCSSMatrix||window.OCSSMatrix;this.info.supports3dTransform=h!=undefined&&(new h).m11!=undefined?true:false};
DisneyGamesHTML5.prototype.isBrowserSupported=function(){for(var h=false,p=0;p<this.minBrowser.length;p++){var x=this.minBrowser[p];if((!x.browserType||this.info.browserName==x.browserType)&&(!x.platformType||this.info.platformType==x.platformType))if(this.info.browserVersion>=x.minVersion&&x.minVersion>0)h=true}return h};var disneyGamesHTML5=new DisneyGamesHTML5;disneyGamesHTML5.detectBrowser(window.navigator);var disneyGamesSwfObject=function(){function h(){if(!N){try{var b=l.getElementsByTagName("body")[0].appendChild(l.createElement("span"));b.parentNode.removeChild(b)}catch(d){return}N=true;b=T.length;for(var f=0;f<b;f++)T[f]()}}function p(b){if(N)b();else T[T.length]=b}function x(b){if(typeof F.addEventListener!=s)F.addEventListener("load",b,false);else if(typeof l.addEventListener!=s)l.addEventListener("load",b,false);else if(typeof F.attachEvent!=s)ca(F,"onload",b);else if(typeof F.onload=="function"){var d=
F.onload;F.onload=function(){d();b()}}else F.onload=b}function r(){var b=l.getElementsByTagName("body")[0],d=l.createElement(J);d.setAttribute("type",V);var f=b.appendChild(d);if(f){var g=0;(function(){if(typeof f.GetVariable!=s){var j=f.GetVariable("$version");if(j){j=j.split(" ")[1].split(",");k.pv=[parseInt(j[0],10),parseInt(j[1],10),parseInt(j[2],10)]}}else if(g<10){g++;setTimeout(arguments.callee,10);return}b.removeChild(d);f=null;B()})()}else B()}function B(){var b=M.length;if(b>0)for(var d=
0;d<b;d++){var f=M[d].id,g=M[d].callbackFn,j={success:false,id:f};if(k.pv[0]>0){var m=H(f);if(m)if(A(M[d].swfVersion)&&!(k.wk&&k.wk<312)){L(f,true);if(g){j.success=true;j.ref=D(f);g(j)}}else if(M[d].expressInstall&&o()){j={};j.data=M[d].expressInstall;j.width=m.getAttribute("width")||"0";j.height=m.getAttribute("height")||"0";if(m.getAttribute("class"))j.styleclass=m.getAttribute("class");if(m.getAttribute("align"))j.align=m.getAttribute("align");var n={};m=m.getElementsByTagName("param");for(var v=
m.length,u=0;u<v;u++)if(m[u].getAttribute("name").toLowerCase()!="movie")n[m[u].getAttribute("name")]=m[u].getAttribute("value");y(j,n,f,g)}else{C(m);g&&g(j)}}else{L(f,true);if(g){if((f=D(f))&&typeof f.SetVariable!=s){j.success=true;j.ref=f}g(j)}}}}function D(b){var d=null;if((b=H(b))&&b.nodeName=="OBJECT")if(typeof b.SetVariable!=s)d=b;else if(b=b.getElementsByTagName(J)[0])d=b;return d}function o(){return!Q&&A("6.0.65")&&(k.win||k.mac)&&!(k.wk&&k.wk<312)}function y(b,d,f,g){Q=true;X=g||null;aa=
{success:false,id:f};var j=H(f);if(j){if(j.nodeName=="OBJECT"){R=w(j);P=null}else{R=j;P=f}b.id=ba;if(typeof b.width==s||!/%$/.test(b.width)&&parseInt(b.width,10)<310)b.width="310";if(typeof b.height==s||!/%$/.test(b.height)&&parseInt(b.height,10)<137)b.height="137";l.title=l.title.slice(0,47)+" - Flash Player Installation";g=k.ie&&k.win?"ActiveX":"PlugIn";g="MMredirectURL="+F.location.toString().replace(/&/g,"%26")+"&MMplayerType="+g+"&MMdoctitle="+l.title;if(typeof d.flashvars!=s)d.flashvars+="&"+
g;else d.flashvars=g;if(k.ie&&k.win&&j.readyState!=4){g=l.createElement("div");f+="SWFObjectNew";g.setAttribute("id",f);j.parentNode.insertBefore(g,j);j.style.display="none";(function(){j.readyState==4?j.parentNode.removeChild(j):setTimeout(arguments.callee,10)})()}t(b,d,f)}}function C(b){if(k.ie&&k.win&&b.readyState!=4){var d=l.createElement("div");b.parentNode.insertBefore(d,b);d.parentNode.replaceChild(w(b),d);b.style.display="none";(function(){b.readyState==4?b.parentNode.removeChild(b):setTimeout(arguments.callee,
10)})()}else b.parentNode.replaceChild(w(b),b)}function w(b){var d=l.createElement("div");if(k.win&&k.ie)d.innerHTML=b.innerHTML;else if(b=b.getElementsByTagName(J)[0])if(b=b.childNodes)for(var f=b.length,g=0;g<f;g++)!(b[g].nodeType==1&&b[g].nodeName=="PARAM")&&b[g].nodeType!=8&&d.appendChild(b[g].cloneNode(true));return d}function t(b,d,f){var g,j=H(f);if(k.wk&&k.wk<312)return g;if(j){if(typeof b.id==s)b.id=f;if(k.ie&&k.win){var m="",n;for(n in b)if(b[n]!=Object.prototype[n])if(n.toLowerCase()==
"data")d.movie=b[n];else if(n.toLowerCase()=="styleclass")m+=' class="'+b[n]+'"';else if(n.toLowerCase()!="classid")m+=" "+n+'="'+b[n]+'"';n="";for(var v in d)if(d[v]!=Object.prototype[v])n+='<param name="'+v+'" value="'+d[v]+'" />';j.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+m+">"+n+"</object>";U[U.length]=b.id;g=H(b.id)}else{v=l.createElement(J);v.setAttribute("type",V);for(var u in b)if(b[u]!=Object.prototype[u])if(u.toLowerCase()=="styleclass")v.setAttribute("class",
b[u]);else u.toLowerCase()!="classid"&&v.setAttribute(u,b[u]);for(m in d)if(d[m]!=Object.prototype[m]&&m.toLowerCase()!="movie"){b=v;n=m;u=d[m];f=l.createElement("param");f.setAttribute("name",n);f.setAttribute("value",u);b.appendChild(f)}j.parentNode.replaceChild(v,j);g=v}}return g}function K(b){var d=H(b);if(d&&d.nodeName=="OBJECT")if(k.ie&&k.win){d.style.display="none";(function(){if(d.readyState==4){var f=H(b);if(f){for(var g in f)if(typeof f[g]=="function")f[g]=null;f.parentNode.removeChild(f)}}else setTimeout(arguments.callee,
10)})()}else d.parentNode.removeChild(d)}function H(b){var d=null;try{d=l.getElementById(b)}catch(f){}return d}function ca(b,d,f){b.attachEvent(d,f);O[O.length]=[b,d,f]}function A(b){var d=k.pv;b=b.split(".");b[0]=parseInt(b[0],10);b[1]=parseInt(b[1],10)||0;b[2]=parseInt(b[2],10)||0;return d[0]>b[0]||d[0]==b[0]&&d[1]>b[1]||d[0]==b[0]&&d[1]==b[1]&&d[2]>=b[2]?true:false}function S(b,d,f,g){if(!(k.ie&&k.mac)){var j=l.getElementsByTagName("head")[0];if(j){f=f&&typeof f=="string"?f:"screen";if(g)Z=E=null;
if(!E||Z!=f){g=l.createElement("style");g.setAttribute("type","text/css");g.setAttribute("media",f);E=j.appendChild(g);if(k.ie&&k.win&&typeof l.styleSheets!=s&&l.styleSheets.length>0)E=l.styleSheets[l.styleSheets.length-1];Z=f}if(k.ie&&k.win)E&&typeof E.addRule==J&&E.addRule(b,d);else E&&typeof l.createTextNode!=s&&E.appendChild(l.createTextNode(b+" {"+d+"}"))}}}function L(b,d){if(W){var f=d?"visible":"hidden";if(N&&H(b))H(b).style.visibility=f;else S("#"+b,"visibility:"+f)}}function Y(b){return/[\\\"<>\.;]/.exec(b)!=
null&&typeof encodeURIComponent!=s?encodeURIComponent(b):b}var s="undefined",J="object",V="application/x-shockwave-flash",ba="SWFObjectExprInst",F=window,l=document,I=navigator,$=false,T=[function(){$?r():B()}],M=[],U=[],O=[],R,P,X,aa,N=false,Q=false,E,Z,W=true,k=function(){var b=typeof l.getElementById!=s&&typeof l.getElementsByTagName!=s&&typeof l.createElement!=s,d=I.userAgent.toLowerCase(),f=I.platform.toLowerCase(),g=f?/win/.test(f):/win/.test(d);f=f?/mac/.test(f):/mac/.test(d);d=/webkit/.test(d)?
parseFloat(d.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):false;var j=!+"\u000b1",m=[0,0,0],n=null;if(typeof I.plugins!=s&&typeof I.plugins["Shockwave Flash"]==J){if((n=I.plugins["Shockwave Flash"].description)&&!(typeof I.mimeTypes!=s&&I.mimeTypes[V]&&!I.mimeTypes[V].enabledPlugin)){$=true;j=false;n=n.replace(/^.*\s+(\S+\s+\S+$)/,"$1");m[0]=parseInt(n.replace(/^(.*)\..*$/,"$1"),10);m[1]=parseInt(n.replace(/^.*\.(.*)\s.*$/,"$1"),10);m[2]=/[a-zA-Z]/.test(n)?parseInt(n.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),
10):0}}else if(typeof F.ActiveXObject!=s)try{var v=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(v)if(n=v.GetVariable("$version")){j=true;n=n.split(" ")[1].split(",");m=[parseInt(n[0],10),parseInt(n[1],10),parseInt(n[2],10)]}}catch(u){}return{w3:b,pv:m,wk:d,ie:j,win:g,mac:f}}();(function(){if(k.w3){if(typeof l.readyState!=s&&l.readyState=="complete"||typeof l.readyState==s&&(l.getElementsByTagName("body")[0]||l.body))h();if(!N){typeof l.addEventListener!=s&&l.addEventListener("DOMContentLoaded",
h,false);if(k.ie&&k.win){l.attachEvent("onreadystatechange",function(){if(l.readyState=="complete"){l.detachEvent("onreadystatechange",arguments.callee);h()}});F==top&&function(){if(!N){try{l.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,0);return}h()}}()}k.wk&&function(){N||(/loaded|complete/.test(l.readyState)?h():setTimeout(arguments.callee,0))}();x(h)}}})();(function(){k.ie&&k.win&&window.attachEvent("onunload",function(){for(var b=O.length,d=0;d<b;d++)O[d][0].detachEvent(O[d][1],
O[d][2]);b=U.length;for(d=0;d<b;d++)K(U[d]);for(var f in k)k[f]=null;k=null;for(var g in disneyGamesSwfObject)disneyGamesSwfObject[g]=null;disneyGamesSwfObject=null})})();return{registerObject:function(b,d,f,g){if(k.w3&&b&&d){var j={};j.id=b;j.swfVersion=d;j.expressInstall=f;j.callbackFn=g;M[M.length]=j;L(b,false)}else g&&g({success:false,id:b})},getObjectById:function(b){if(k.w3)return D(b)},embedSWF:function(b,d,f,g,j,m,n,v,u,a){var c={success:false,id:d};if(k.w3&&!(k.wk&&k.wk<312)&&b&&d&&f&&g&&
j){L(d,false);p(function(){f+="";g+="";var e={};if(u&&typeof u===J)for(var q in u)e[q]=u[q];e.data=b;e.width=f;e.height=g;q={};if(v&&typeof v===J)for(var G in v)q[G]=v[G];if(n&&typeof n===J)for(var z in n)if(typeof q.flashvars!=s)q.flashvars+="&"+z+"="+n[z];else q.flashvars=z+"="+n[z];if(A(j)){G=t(e,q,d);e.id==d&&L(d,true);c.success=true;c.ref=G}else if(m&&o()){e.data=m;y(e,q,d,a);return}else L(d,true);a&&a(c)})}else a&&a(c)},switchOffAutoHideShow:function(){W=false},ua:k,getFlashPlayerVersion:function(){return{major:k.pv[0],
minor:k.pv[1],release:k.pv[2]}},hasFlashPlayerVersion:A,createSWF:function(b,d,f){if(k.w3)return t(b,d,f)},showExpressInstall:function(b,d,f,g){k.w3&&o()&&y(b,d,f,g)},removeSWF:function(b){k.w3&&K(b)},createCSS:function(b,d,f,g){k.w3&&S(b,d,f,g)},addDomLoadEvent:p,addLoadEvent:x,getQueryParamValue:function(b){var d=l.location.search||l.location.hash;if(d){if(/\?/.test(d))d=d.split("?")[1];if(b==null)return Y(d);d=d.split("&");for(var f=0;f<d.length;f++)if(d[f].substring(0,d[f].indexOf("="))==b)return Y(d[f].substring(d[f].indexOf("=")+
1))}return""},expressInstallCallback:function(){if(Q){var b=H(ba);if(b&&R){b.parentNode.replaceChild(R,b);if(P){L(P,true);if(k.ie&&k.win)R.style.display="block"}X&&X(aa)}Q=false}}}}();


}
/*
     FILE ARCHIVED ON 01:18:17 Nov 30, 2012 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 22:26:27 Sep 13, 2024.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 0.693
  exclusion.robots: 0.029
  exclusion.robots.policy: 0.013
  esindex: 0.012
  cdx.remote: 8.561
  LoadShardBlock: 38.676 (3)
  PetaboxLoader3.datanode: 55.529 (4)
  load_resource: 85.589
  PetaboxLoader3.resolve: 45.779
*/